language: java

sudo: false

jdk:
  - openjdk8

branches:
  only:
    - travis-ci
    
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- df -h
- echo $deployuser

script: mvn clean install -q
