#!/bin/bash

# Cytoscape DMG Signing script
# Author: Brett Settle
# Date: March 27, 2018
# Email: bsettle @ ucsd

# To use this script:
# Run `mvn clean install` in the gui-distribution/packaging directory to
# generate installers. Ensure the variables below are valid, then run
# `./sign-dmg.sh` to generate a signed dmg in the target/install4j/signed
# directory.


# This script must be run on a Mac, with a certificate in the keychain named:
#	"Developer ID Application: The Cytoscape Consortium" created by Barry Demchak
# Expires Mar 28, 2023
# Download from https://developer.apple.com/account/mac/certificate/


# NOTE: Apple Developer site claims that you need 2 certs in your keychain
# for the Developer ID Application to work.
# 	Worldwide Developer Relations Certificate Authority:
#			https://developer.apple.com/certificationauthority/AppleWWDRCA.cer
#		Developer ID Certificate Authority:
#			https://developer.apple.com/certificationauthority/DeveloperIDCA.cer


SEP="----------"
function section {
	echo
	echo "${SEP} $1 ${SEP}"
	echo
}

# Identity Common Name in Keychain
SIGNING_IDENTITY=${1:-"Developer ID Application"}
# Location of dmg generated by `mvn clean install`
ORIGINAL_DMG=`ls target/install4j/Cytoscape_*_macos.dmg`
# dirs for generating signed dmg
MOUNT_DIR=target/mount
SIGN_DIR=target/tempsign
TARGET_DIR=target/install4j/signed
TARGET_DMG="${TARGET_DIR}/$(basename ${ORIGINAL_DMG})"

section "Creating signed ${ORIGINAL_DMG} at ${TARGET_DMG}"

mkdir -p "${MOUNT_DIR}"
mkdir -p "${SIGN_DIR}"
mkdir -p "${TARGET_DIR}"

section "Mounting original DMG..."

DEVICE=$(hdiutil attach -noverify -noautoopen -mountroot `pwd`/${MOUNT_DIR} ${ORIGINAL_DMG} | egrep '^/dev/' | sed 1q | awk '{print $1}') || exit 1

VOLUME_DIR="$(basename ${MOUNT_DIR}/Cytoscape*)"

section "Extracting installer..."

cp -r ${MOUNT_DIR}/Cytoscape*/Cytoscape\ Installer.app "${SIGN_DIR}"
hdiutil detach "${DEVICE}"


section "Signing installer..."

rm ${SIGN_DIR}/Cytoscape\ Installer.app/Contents/vmoptions.txt

codesign -f -s "${SIGNING_IDENTITY}" "${SIGN_DIR}"/Cytoscape\ Installer.app
codesign -vvv "${SIGN_DIR}"/Cytoscape\ Installer.app || exit 1
spctl -a -t open --context context:primary-signature -v "${SIGN_DIR}"/Cytoscape\ Installer.app || exit 1

section "Creating new DMG in \"${TARGET_DIR}\"..."

rm -f "${TARGET_DMG}" 2>&1 >/dev/null
rm -f target/temp.dmg 2>&1 >/dev/null

hdiutil create -srcfolder "${SIGN_DIR}" -volname "${VOLUME_DIR}" -fs HFS+J -fsargs "-c c=64,a=16,e=16" -format UDRW target/temp.dmg || exit 1
hdiutil convert target/temp.dmg -format UDZO -imagekey zlib-level=9 -o "${TARGET_DMG}" || exit 1

rm target/temp.dmg 2>&1 >/dev/null
rmdir target/mount
rm -rf target/tempsign

section "Done!"
